"""Типизированные модели ответов API.

По файлу на домен: платежи, возвраты, чеки, выплаты, сделки, счета.
"""

from __future__ import annotations

from .base import (
    Model,
    ModelClass,
    parse_datetime,
    parse_decimal,
)
from .common import (
    Amount,
    AuthorizationDetails,
    BankCardData,
    BankCardProduct,
    CancellationDetails,
    Confirmation,
    PayerBankDetails,
    Recipient,
    Settlement,
    ThreeDSecureDetails,
    Transfer,
)
from .deal import Deal
from .misc import (
    DeliveryMethod,
    Invoice,
    InvoicePaymentDetails,
    LineItem,
    PersonalData,
    PosLink,
    PosLinkPayment,
    SbpBank,
    SelfEmployed,
)
from .page import Page
from .payment import (
    PAYMENT_METHOD_MODELS,
    B2bSberbankVatData,
    ElectronicCertificate,
    ElectronicCertificateApprovedPaymentArticle,
    ElectronicCertificatePayment,
    InvoiceDetails,
    Payment,
    PaymentDealInfo,
    PaymentMethod,
    PaymentMethodAlfabank,
    PaymentMethodAlfaPay,
    PaymentMethodApplePay,
    PaymentMethodB2bSberbank,
    PaymentMethodBankCard,
    PaymentMethodCash,
    PaymentMethodConfirmation,
    PaymentMethodElectronicCertificate,
    PaymentMethodGooglePay,
    PaymentMethodInstallments,
    PaymentMethodMobileBalance,
    PaymentMethodQiwi,
    PaymentMethodSberbank,
    PaymentMethodSberBnpl,
    PaymentMethodSberLoan,
    PaymentMethodSbp,
    PaymentMethodTinkoffBank,
    PaymentMethodWebmoney,
    PaymentMethodWeChat,
    PaymentMethodYooMoney,
)
from .payout import (
    IncomeReceipt,
    Payout,
    PayoutCardData,
    PayoutDealInfo,
    PayoutDestination,
    PayoutSelfEmployedInfo,
)
from .receipt import (
    IndustryDetails,
    MarkCodeInfo,
    MarkQuantity,
    OperationalDetails,
    Receipt,
    ReceiptItem,
    ReceiptItemSupplier,
)
from .refund import (
    ElectronicCertificateRefundArticle,
    ElectronicCertificateRefundData,
    Refund,
    RefundAuthorizationDetails,
    RefundDealInfo,
    RefundMethod,
    RefundSource,
)
from .shop import (
    FiscalizationData,
    Me,
    Webhook,
)

__all__ = [
    "Amount",
    "AuthorizationDetails",
    "B2bSberbankVatData",
    "BankCardData",
    "BankCardProduct",
    "CancellationDetails",
    "Confirmation",
    "Deal",
    "DeliveryMethod",
    "ElectronicCertificate",
    "ElectronicCertificateApprovedPaymentArticle",
    "ElectronicCertificatePayment",
    "ElectronicCertificateRefundArticle",
    "ElectronicCertificateRefundData",
    "FiscalizationData",
    "IncomeReceipt",
    "IndustryDetails",
    "Invoice",
    "InvoiceDetails",
    "InvoicePaymentDetails",
    "LineItem",
    "MarkCodeInfo",
    "MarkQuantity",
    "Me",
    "Model",
    "ModelClass",
    "OperationalDetails",
    "Page",
    "parse_datetime",
    "parse_decimal",
    "PayerBankDetails",
    "Payment",
    "PaymentDealInfo",
    "PaymentMethod",
    "PaymentMethodAlfabank",
    "PaymentMethodAlfaPay",
    "PaymentMethodApplePay",
    "PaymentMethodB2bSberbank",
    "PaymentMethodBankCard",
    "PaymentMethodCash",
    "PaymentMethodConfirmation",
    "PaymentMethodElectronicCertificate",
    "PaymentMethodGooglePay",
    "PaymentMethodInstallments",
    "PaymentMethodMobileBalance",
    "PaymentMethodQiwi",
    "PaymentMethodSberbank",
    "PaymentMethodSberBnpl",
    "PaymentMethodSberLoan",
    "PaymentMethodSbp",
    "PaymentMethodTinkoffBank",
    "PaymentMethodWebmoney",
    "PaymentMethodWeChat",
    "PaymentMethodYooMoney",
    "PAYMENT_METHOD_MODELS",
    "Payout",
    "PayoutCardData",
    "PayoutDealInfo",
    "PayoutDestination",
    "PayoutSelfEmployedInfo",
    "PersonalData",
    "PosLink",
    "PosLinkPayment",
    "Receipt",
    "ReceiptItem",
    "ReceiptItemSupplier",
    "Recipient",
    "Refund",
    "RefundAuthorizationDetails",
    "RefundDealInfo",
    "RefundMethod",
    "RefundSource",
    "SbpBank",
    "SelfEmployed",
    "Settlement",
    "ThreeDSecureDetails",
    "Transfer",
    "Webhook",
]
